name: deepfake
description: A Flutter app for detecting audio deepfakes.

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Ensure compatibility with the latest stable Dart SDK

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # Firebase Dependencies (kept for authentication if needed)
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_dynamic_links: 6.1.4
  
  # Authentication
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.0
  
  # State Management
  provider: ^6.1.2
  
  # File handling
  file_picker: ^10.1.2  # For picking audio files
  
  # TensorFlow Lite for model inference
  tflite_flutter: ^0.11.0

  http_parser: ^4.1.2
  
  # Audio processing libraries
  just_audio: ^0.10.1  # For audio playback and basic processing
  # flutter_audio_capture: ^1.1.9  # For audio capture
  wav: ^1.4.0  # For WAV file processing
  
  # Added for audio spectrum analysis (new)
  #flutter_fft: ^1.0.2+1  For FFT operations to generate frequency data

  audio_waveforms: ^1.3.0

  # fftea: ^1.5.0+1

  # complex: ^0.8.0
  
  # Added for file system operations (new)
  path: ^1.9.1  # For file path operations
  
  # Added for permissions handling (new)
  permission_handler: ^12.0.0+1 # For requesting storage and microphone permissions

  # Storage
  shared_preferences: ^2.2.0  # Moved from dev_dependencies
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0  # Moved from dependencies as it's a development tool
  http: ^1.3.0
  mime: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/images/
    - lib/models/audio_deepfake_model.tflite  # TFLite model for deepfake detection