// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAzYLuvz0-tZ0dImBnquJGPdAcnLb9x18',
    appId: '1:788480188250:web:51da8c00f964ffa2e29d63',
    messagingSenderId: '788480188250',
    projectId: 'oauth-2c942',
    authDomain: 'oauth-2c942.firebaseapp.com',
    storageBucket: 'oauth-2c942.firebasestorage.app',
    measurementId: 'G-4C58BV5LR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAnh_bi2ZV09igQjB4IIxrCOzTY117Z4U',
    appId: '1:788480188250:android:4a2b1f2336ab92aee29d63',
    messagingSenderId: '788480188250',
    projectId: 'oauth-2c942',
    storageBucket: 'oauth-2c942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDprA5sMgKzUToN5C7agO94Ved-9YV35Q0',
    appId: '1:788480188250:ios:02f04637b86fa9bae29d63',
    messagingSenderId: '788480188250',
    projectId: 'oauth-2c942',
    storageBucket: 'oauth-2c942.firebasestorage.app',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDprA5sMgKzUToN5C7agO94Ved-9YV35Q0',
    appId: '1:788480188250:ios:02f04637b86fa9bae29d63',
    messagingSenderId: '788480188250',
    projectId: 'oauth-2c942',
    storageBucket: 'oauth-2c942.firebasestorage.app',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAzYLuvz0-tZ0dImBnquJGPdAcnLb9x18',
    appId: '1:788480188250:web:d1e45e769fc38098e29d63',
    messagingSenderId: '788480188250',
    projectId: 'oauth-2c942',
    authDomain: 'oauth-2c942.firebaseapp.com',
    storageBucket: 'oauth-2c942.firebasestorage.app',
    measurementId: 'G-Q70XZ4FJMS',
  );
}
